# config/packages/doctrine.yaml
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'  # ✅ Correct DBAL option
        use_savepoints: true                           # ✅ Correct DBAL option
        # Add mapping_types here if needed
        types:
            enum: Doctrine\DBAL\Types\StringType       # ✅ Define custom types under DBAL

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        enable_lazy_ghost_objects: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

# Remove these invalid ORM options:
# ❌ profiling_collect_backtrace: '%kernel.debug%'
# ❌ use_savepoints: true
# ❌ mapping_types: { enum: string }

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.project_dir%/var/doctrine/Proxies'  # Better path
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system