# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    http_client:
        scoped_clients:
            my_client:
                base_uri: 'https://api-inference.huggingface.co'
                
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

    trusted_hosts:
        - ^localhost$
        - ^127\.0\.0\.1$
        - ^[a-zA-Z0-9-]+\.ngrok-free\.app$
        - ^[a-zA-Z0-9-]+\.ngrok\.io$
