# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

    trusted_hosts:
        - ^localhost$
        - ^127\.0\.0\.1$
        - ^[a-zA-Z0-9-]+\.ngrok-free\.app$
        - ^[a-zA-Z0-9-]+\.ngrok\.io$
