# config/packages/scheb_2fa.yaml
scheb_two_factor:
    google:
        enabled: true
        server_name: Your App Name
        issuer: Your Company Name
        template: security/2fa_form.html.twig
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Core\Authentication\Token\RememberMeToken