# config/packages/security.yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        public:
            pattern: ^/(login|2fa)$  # Removed connect from here
            security: false

        connect:
            pattern: ^/connect
            security: true
            stateless: false
            entry_point: App\Security\GoogleAuthenticator
            provider: app_user_provider
            custom_authenticators:
                - App\Security\GoogleAuthenticator
            access_denied_handler: App\Security\AccessDeniedHandler
            context: main


        main:
#            anonymous: true
            pattern: ^/
            lazy: true
            provider: app_user_provider
            context: main
#            form_login:
#                login_path: app_user_login
#                check_path: app_user_login
#                enable_csrf: true
#                username_parameter: email  # Use 'email' instead of '_username'
#                password_parameter: password

            # Two-factor authentication
            two_factor:
                auth_form_path: 2fa_login        # Route to display 2FA form
                check_path: 2fa_check            # Route to submit 2FA code
                default_target_path: app_profile  # Where to redirect after success
                always_use_default_target_path: false
                auth_code_parameter_name: _auth_code

            logout:
                path: app_logout
                target: app_home
                invalidate_session: true
                delete_cookies:
                    - PHPSESSID
                    - REMEMBERME
                csrf_token_generator: security.csrf.token_manager

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
        - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: ^/connect/google, roles: PUBLIC_ACCESS }
        - { path: ^/connect/google/check, roles: PUBLIC_ACCESS }
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: PUBLIC_ACCESS }
        - { path: ^/verify/email, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/check-email, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10