# config/packages/twig.yaml

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    cache: '%kernel.cache_dir%/twig'
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    paths: # Optional, if you have custom paths
        '%kernel.project_dir%/templates': ~
    globals: # Optional, if you need global variables
        app_name: 'MyApp'

services:
    Twig\Extra\TwigExtraBundle\String\StringExtension: ~ # Ensure StringExtension is enabled
