vich_uploader:
    db_driver: orm
    mappings:
        medecin:
            uri_prefix: /uploads/medecins
            upload_destination: '%kernel.project_dir%/public/uploads/medecins'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer: Vich\UploaderBundle\Naming\SubdirDirectoryNamer
            delete_on_update: true
            delete_on_remove: true
