# config/packages/web_profiler.yaml

web_profiler:
    intercept_redirects: false

when@dev:
    web_profiler:
        toolbar: false
        intercept_redirects: false

when@test:
    web_profiler:
        toolbar: false
