controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_login:
    path: /login
    controller: App\Controller\UserController::login
    methods: [GET, POST]

app_logout:
    path: /logout

connect_google:
    path: /connect/google
    controller: KnpU\OAuth2ClientBundle\Controller\ConnectController::connectAction

connect_google_check:
    path: /connect/google/check
    controller: KnpU\OAuth2ClientBundle\Controller\ConnectController::connectCheckAction
