controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
app_trips_index:
    path: /voyages
    controller: App\Controller\TripsController::index

app_trips_show:
    path: /voyage/{id}
    controller: App\Controller\TripsController::show
    requirements:
        id: '\d+'

app_trips_search:
    path: /recherche
    controller: App\Controller\TripsController::search

    # config/routes.yaml
api_seat_configuration:
    path: /api/seat-configuration/{tripId}
    controller: App\Controller\ReservationsController::getSeatConfiguration
    methods: GET
apply_reward:
  path: /api/apply-reward
  controller: App\Controller\RewardApiController::apply
  methods: [POST]
