parameters:
    profile_pictures_directory: '%kernel.project_dir%/public/uploads/profile_pictures'
    images_directory: '%kernel.project_dir%/public/uploads/images'

services:
    # Default configuration for services in the `src/` directory
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%profile_pictures_directory%'
            $slugger: '@slugger'

    app.oauth_user_provider:
        class: App\Security\OAuthUserProvider
        arguments: [ '@doctrine.orm.entity_manager' ]

    App\Service\CurrentUserService:
        autowire: true
        autoconfigure: true
        public: true

    App\Twig\AppExtension:
            arguments: [ '@App\Service\CurrentUserService' ]
            tags: [ 'twig.extension' ]

    App\Security\GoogleAuthenticator:
        autowire: true
        autoconfigure: true
        public: true

    App\Repository\UserRepository:
        arguments:
            - '@doctrine'
            - '@doctrine.orm.entity_manager'
            - '@security.user_password_hasher'
        tags: ['doctrine.repository_service']

    App\Controller\HomeController:
        autowire: true
        autoconfigure: true
        public: true

    App\Controller\BlogPostController:
        autowire: true
        autoconfigure: true
        public: true

    App\Repository\BlogPostRepository:
        class: App\Repository\BlogPostRepository
        arguments:
            - '@doctrine'

    App\Controller\UserController:
        autowire: true
        autoconfigure: true
        public: true
        tags: ['controller.service_arguments']

    App\Service\EmailService:
        arguments:
            $mailer: '@mailer'
            $logger: '@logger'
            $twig: '@twig'

    App\Controller\BaseController:
        autowire: true
        autoconfigure: true
        public: true
        tags: ['controller.service_arguments']

