parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'

services:
    # Default configuration for services in the `src/` directory
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'
        autowire: true
        autoconfigure: true
    App\Service\ContentFilterService:
        arguments:
            $httpClient: '@http_client'

    # You can add more service definitions here if needed

