parameters:
    profile_pictures_directory: '%kernel.project_dir%/public/uploads/profile_pictures'
    images_directory: '%kernel.project_dir%/public/uploads/images'
    trips_images_directory: '%kernel.project_dir%/public/uploads/trips'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'


    
services:
    # Default configuration for services in the `src/` directory
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.



    Symfony\Component\Finder\Finder: ~
    # Définition du service annotation_reader
    annotation_reader:
        class: Doctrine\Common\Annotations\AnnotationReader
        public: false

    # Configuration par défaut pour les services dans ce fichier
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Rendre disponibles les classes de src/ en tant que services
    # Cela crée un service par classe dont l'identifiant est le nom de classe complet
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%profile_pictures_directory%'
            $slugger: '@slugger'

    app.oauth_user_provider:
        class: App\Security\OAuthUserProvider
        arguments: [ '@doctrine.orm.entity_manager' ]

    App\Service\CurrentUserService:
        autowire: true
        autoconfigure: true
        public: true

    App\Twig\AppExtension:
            arguments: [ '@App\Service\CurrentUserService' ]
            tags: [ 'twig.extension' ]

    App\Security\GoogleAuthenticator:
        autowire: true
        autoconfigure: true
        public: true

    App\Repository\UserRepository:
        arguments:
            - '@doctrine'
            - '@doctrine.orm.entity_manager'
            - '@security.user_password_hasher'
        tags: ['doctrine.repository_service']

    App\Controller\HomeController:
        autowire: true
        autoconfigure: true
        public: true

    App\Controller\BlogPostController:
        autowire: true
        autoconfigure: true
        public: true

    App\Repository\BlogPostRepository:
        class: App\Repository\BlogPostRepository
        arguments:
            - '@doctrine'
        tags: ['doctrine.repository_service']

    App\Repository\ProductRepository:
        class: App\Repository\ProductRepository
        arguments:
            - '@doctrine'
        tags: ['doctrine.repository_service']

    App\Repository\OrderRepository:
        class: App\Repository\OrderRepository
        arguments:
            - '@doctrine'
        tags: ['doctrine.repository_service']

    App\Controller\UserController:
        autowire: true
        autoconfigure: true
        public: true
        tags: ['controller.service_arguments']

    App\Controller\ProductController:
        autowire: true
        autoconfigure: true
        public: true
        tags: ['controller.service_arguments']

    App\Controller\OrderController:
        autowire: true
        autoconfigure: true
        public: true
        tags: ['controller.service_arguments']

    App\Service\EmailService:
        arguments:
            $mailer: '@mailer'
            $logger: '@logger'
            $twig: '@twig'

    App\Security\UserChecker:
        tags: [ security.user_checker ]

    App\Controller\BaseController:
        autowire: true
        autoconfigure: true
        public: true
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    # Ajoute ici d'autres définitions de services si nécessaire.
