# config/services.yaml
parameters:
    # Seuils : nombre de trajets => type de récompense
    reward.thresholds:
        5:   'small_discount'
        10:  'medium_discount'
        15:  'big_discount'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            # Par défaut, on pourrait binder d’autres scalaires si besoin

    # Configuration explicite de RewardConfig
    App\Service\RewardConfig:
        arguments:
            $seuils: '%reward.thresholds%'

    # ProgressService reste en autowire
    App\Service\ProgressService: ~

    # Reste des services dans src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
